### PR TITLE
Support GNOME 3.28.

### PR DESCRIPTION
**Pull request by marxin**
I've just tested the version and it works fine.

### CODE REVIEW

**Comment by franglais125** [comment]
Thanks!

**Comment by gugaiz** [comment]
Are you going to merge this? Ubuntu 18.04 is about to see the light and this extension is not listed as supported on 3.28.

**Comment by franglais125** [comment]
It was already merged.

We need to upload a new version to extensions.gnome.org. I'll probably need to ping @chrisspen or a reviewer.

**Comment by chrisspen** [comment]
@franglais125 Is it ready for a release? I try not to upload too often, because it seems like a lot of bugs slip through.

**Comment by franglais125** [comment]
The new "release" is not really that big. We only had 9 commits since v33...

That being said, the quickest approach to support Gnome 3.28 (not just Ubuntu) is to upload a new version with the metadata modification **only**. For instance, I did just that for another extension I maintain. By doing so ,we avoid getting stuck on the review list, which can take a long time these days.

Modifications to metadata and translation files get auto-approved.

See my example from today: https://extensions.gnome.org/review/8040

**Comment by piegamesde** [comment]
Only updating the metadata is not enough IMO. There were a few bugs fixed since then (the tooltips, the log warnings, the frequency reading, the spacing, ...) that shouldn't be ignored.

**Comment by chrisspen** [comment]
@franglais125 [This user](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/202#issuecomment-378898549) reported that the current git master is unusable on his platform.

**Comment by franglais125** [comment]
@piegamesde : Ideally we wojld of course include all the fixes, I'm not against that. What I'm proposing *for now* is to make a release that merely advertises 3.28 support. Such releases get automatically approved. If we include any other fix, we will get stuck in the review queue for days/weeks/months (take a look here extensions.gnome.org/review). The goal here, frlm my perspective, is to give access to this extension to people running 3.28 as soon as possible.

Once this is done, we can *then* look at making a new release with actual code modifications: features, fixes, changes,etc. Now this next version *will* indeed go through the review queue, as usual.

----------------------
@chrisspen : I hope the above ecplanation addresses your concern as well. The new release I propose (until we are ready for an "actual" release) won't change anything for that user, nor for anyone else, as only the metadata will have changed (adding 3.28 support). I'll comment on that separate issue soon, not to conflate everything here.

**Comment by chrisspen** [comment]
@franglais125 I take your point. I agree, it's a good idea to make a release just to change some metadata that will update gnome support. However, that would require pushing up master, right? Have the commits made to master since the last release caused the problems in issue 202? If they have, even a release to change metadata would introduce other changes. The solution to this is to adopt a new branching strategy that would keep all merged fixes in a dedicated "develop" branch, so we can push up minor fixes to master without deploying other untested changes.

**Comment by p91paul** [comment]
@chrisspen if there isn't a tag of the last released version on e.g.o. you can just download the zip file from e.g.o., edit metadata.json and reupload it.

**Comment by piegamesde** [comment]
As far as I know, #202 does affect almost all users, not only one person. The fix provided by @franglais125 is still not in the master. Also, the fix has a bug that consumes file pointers until Gnome crashes and restarts, which is way worse than the original bug.

**Comment by franglais125** [comment]
I tagged v35: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/releases/tag/v35

With respect to the latest upload, this only contains a modification to the metadata file.

**Comment by chrisspen** [comment]
@franglais125 I've uploaded your tag for review.

**Pull request merged**
