### PR TITLE
Fix battery error and crash

### PR DESCRIPTION
**Pull request by NVieville**
Hello,

This pull request do exactly what was provided in the patch in issue #400.

Cordially,

-- 
NVieville

### CODE REVIEW

**Comment by chrisspen** [comment]
@franglais125 Can you confirm this? Do you know why the current index used in the code isn't causing more problems?

**Comment by franglais125** [comment]
It's weird that we have this issue, and nobody complained earlier. I used the built-in battery indicator anyway, so perhaps I just didn't hit this problem.

We don't even seem to have that many indices for `this.menu_items[]`, just `0` and `1`. So I really don't know where `3` comes from.

Running `git blame` for the line we are changing takes me back to a commit from 2012, so many things might have changed since.

This being said, I'll check more carefully later today/tomorrow.

Thanks @NVieville for spotting this and for the PR!

**Comment by NVieville** [comment]
@franglais125 You're welcome.
The difference was made by commit 8a9419440693b0eea9c2bde4b3bca2176609460e on 10 April 2017.
This one removed some "new St.Label()", in the create_menu_items function below line 1116, that led to have less items in "this.menu_items[]". Index 3 at line 1105 was here earlier, but from this commit it didn't point to an element of the "this.menu_items[]" array.
Glad to help.
Cordially,


-- 
NVieville

**Comment by franglais125** [comment]
I can now confirm the issue and the fix.

I wasn't seeing this as I don't use the battery module. Well done @NVieville !

Here is the JS error from the log:
```
JS ERROR: TypeError: this.menu_items[3] is undefined
                                        Battery<._apply@/home/franglais125/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/extension.js:1105
```

**Comment by chrisspen** [comment]
Thanks @franglais125

**Pull request merged**
