### PR TITLE
GPU usage: show usage when using glxinfo output

### PR DESCRIPTION
**Pull request by psukys**
Previously glxinfo only output total and used memory when using glxinfo, but the nvidia output as well contained usage information, this pull request simply adds that additional third - utilization - data outptu

### CODE REVIEW

**Comment by DevDef** [comment]
Your calculation relies on `bc`. This is adding a dependency. Could you make it without bc?

**Comment by DevDef** [comment]
The following is POSIX shell without dependencies (although it’s limited to integer values):
`echo $(( FREEVRAM * 100 / TOTALVRAM ))`

**Comment by psukys** [comment]
bc is part of posix

**Comment by DevDef** [comment]
It’s not installed by default on all systems, so it is a problem. As managing external dependencies on each and every system is painful, it’s better not to add one more dependency that is not essential.

**Comment by chrisspen** [comment]
For the reason @DevDef has pointed out, I don't think change is appropriate. You're introducing an external tool to do something as trivial as calculate a decimal. Javascript can easily do this.

If you want to calculate this in Javascript or a more universally supported method, that wouldn't be a problem. Closing this for now. Feel free to re-open if you want to update it.

**Pull request closed without merging**
