### PR TITLE
Fix Travis CI docker hang

### PR DESCRIPTION
**Pull request by braewoods**

### CODE REVIEW

**Comment by braewoods** [comment]
It now "succeeds" as far as Travis CI is concerned. See here: https://travis-ci.com/github/braewoods/gnome-shell-system-monitor-applet/builds/229275759

**Comment by chrisspen** [comment]
Thanks. If the chown command is the only fix, could you remove all the other unrelated JS changes? They're probably fine, but I'd like to keep this PR isolated to the CI build, and not address any other issues.

**Comment by braewoods** [comment]
@chrisspen Ok. It's done. I've isolated this to just my commit.

**Comment by chrisspen** [comment]
Thanks.

**Pull request merged**
