### PR TITLE
Support Gnome 41.

### LINKED ISSUE #717: Support GNOME 41
After updating to Gnome 41, I see the following error:
`Gtk.VBox is not a constructor`. Which is likely related to fack that `VBox` is deprecated:
https://docs.gtk.org/gtk3/class.VBox.html

### PR DESCRIPTION
**Pull request by marxin**
Tested on openSUSE Tumbleweed.
Fixes #717.

### CODE REVIEW

**Comment by jhaiduce** [comment]
This seems to be fixed in the master branch, but it looks like the fix hasn't reached extensions.gnome.org yet. Plus Gnome Extensions seems to be getting more aggressive about updating extensions, so when I install from master it keeps getting replaced by the version at extensions.gnome.org.

Can someone push the fix to extensions.gnome.org so we can just install from there?

In the meantime does anyone know a way to keep Gnome Extensions from "upgrading" the extension to the version at extensions.gnome.org?

**Comment by p91paul** [comment]
you can manually set "version" to 1000 or some other high number in metadata.json, to make e.g.o. think you are on a higher version

**Comment by jhaiduce** [comment]
> you can manually set "version" to 1000 or some other high number in metadata.json, to make e.g.o. think you are on a higher version

That helped, thanks.

**Comment by 190n** [comment]
Is there an ETA on when the GNOME 41 version will be published to extensions.gnome.org?

**Comment by marxin** [comment]
> Is there an ETA on when the GNOME 41 version will be published to extensions.gnome.org?

Very good question. I guess @chrisspen can help us?

**Pull request merged**
