### PR TITLE
Use kbit/s instead of kbps

### PR DESCRIPTION
**Pull request by franglais125**
Hi,

This PR is a proposal to change
- `kbps` to `kbit/s`
- `Mbps` to `Mbit/s`

as the units shown when using the option "Show network speed in bits". This was originally proposed by @DevDef in issue #359.

The second commit in this PR is simply updating the general file for translations, so that it's easier to track strings that need to be translated.

### CODE REVIEW

**Comment by franglais125** [comment]
I have added a fix for #360 . @DevDef Do you mind testing if this is ok, and if there are other numbers I might have missed?

**Comment by DevDef** [comment]
There’s currently a bug in the GNOME 3.24 JavaScript back-end (mozjs38) when calling the Number.toLocaleString() method with no argument. What you did probably works on previous GNOME versions, but it doesn’t work for GNOME 3.24 (see [this discussion](https://github.com/jenslody/gnome-shell-extension-openweather/issues/184#issuecomment-296442405) and this [Mozilla bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=999003)).
The workaround is to get the current user’s locale and give it as an argument for the Number.toLocaleString() method (see [this patch](https://github.com/jenslody/gnome-shell-extension-openweather/issues/184#issuecomment-296442405) for gnome-shell-extension-openweather).

BTW, I wonder how we can translate the string “Display system informations in gnome shell status bar, such as memory usage, cpu usage, network rate…” (should rather be “Display system informations in **GNOME** shell status bar, such as memory usage, **CPU** usage, network rates…”, BTW) that is located in [metadata.json](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/blob/master/system-monitor%40paradoxxx.zero.gmail.com/metadata.json) and that is displayed in the _Extensions_ tab of the GNOME Tweak tool.

Lastly, I completely agree that we need the fix you provided for the issue #355. ;-)

**Comment by DevDef** [comment]
Please see my pull request #372 that fixes the issue with GNOME 3.24.

**Comment by franglais125** [comment]
@DevDef Thanks for the checks! I cherry-picked and squashed your commits from the other PR in [bb4832f6921c5060e0118b18a3329591e681c4c1].

**Comment by franglais125** [comment]
@chrisspen I removed the Locale fix from this PR, as it had conflicts with the other PR I opened.

I moved the fixes to https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/375.

On this way, this PR does what the title says: it simply changes the units from kbps to kbit/s, etc.
[09bc07e4653cd4b4ef3a58950c9f0063fa0f388c] and [998f6f963514b8dd21e45a78cee2bde09bd37d9b]

**Pull request merged**
