### PR TITLE
Update fedora related info to current fedora

### PR DESCRIPTION
**Pull request by HinTak**
Updating info to current fedora (32)

### CODE REVIEW

**Comment by HinTak** [comment]
Ping - Ci seems to be broken since May!

**Comment by tlwhitec** [comment]
How about updating it for Fedora 33 as well ;) (as a benefit, new commit will retrigger Travis)
I'll be closing my PR in favor of yours.

**Comment by HinTak** [comment]
Ci still broken, somebody filed issue with ci, don't know if related : https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/636

**Comment by DevDef** [comment]
I’ve included your changes in #662.
@chrisspen This PR can be closed.

**Comment by HinTak** [comment]
@DevDef if you had pulled this into your pull (instead of re-adding the same change under your name), when your pull get merged this will be closed too. In any case, this pull can also be merged since it is now a no-op, if you had taken the change as is, without editing.

**Comment by DevDef** [comment]
@HinTak Thanks for the advice. I’m not a Git master, still a padawan. I’ll try this method next time.

**Comment by HinTak** [comment]
@DevDef for what git was invented for - the Linux kernel - the way you did it, claiming others' work as your own / without acknowledging source of change, was very much frown upon. Because of copyright /patent threats, git was invented to be able to trace who/where a line came from.

It was also, from day-one, able to cope with duplicated changes across different merges: e.g.sometimes both the wifi subsystem and the bluetooth subsystem needs /depends on a change from the network core, but it is not mature enough for linus' tree yet; then both the wifi branch and the bluetooth branch would pull in / cherry-pick the in-dev network core; and by the time both branches are merged, git is clever enough to spot identical changes in both and just ignore the later portion. There is no need to skip / apply duplicate changes by hand, nor put others' work under your name.

Being able to automatically close pulls if another merge includes it, is a github thing (as opposed to a git functionality). But I have seen it first-hand (as in pull anothers' into mine, when mine get merged to main, the other pull also closes)

**Comment by DevDef** [comment]
So, can someone close this PR now?

**Comment by HinTak** [comment]
@chrisspen for what is worth, I would prefer a no-op merge, to preserve   history and credit, as I explained above, instead of simply closing.

**Pull request closed without merging**
