### PR TITLE
Fixed thermal sensor dropdown label rendering.

### PR DESCRIPTION
**Pull request by chrisspen**
Fixed rendering of the thermal dropdown text in Gnome ~3.28.4 inspired by PR #674.

### CODE REVIEW

**Comment by bluet** [comment]
@chrisspen  Cool. I was experiencing the problem with all drop-down labels but couldn't find where to fix it.

Thanks for your fix! 🎉

**Comment by bluet** [comment]
@chrisspen could you also fix other drop-down menus this way in the PR?

**Comment by chrisspen** [comment]
@bluet The thermal sensor dropdown is the only one broken for me in Ubuntu 18. What other ones are broken?

I didn't already merge this because I'm not sure it doesn't break anything in more recent Gnome versions.

**Comment by bluet** [comment]
@chrisspen the Fan one seems broken too
2021-04-07 21-23-36 的螢幕擷圖

**Comment by chrisspen** [comment]
@bluet It works for me. Which OS/Gnome version are you using?

**Comment by bluet** [comment]
@chrisspen just did another test again with the latest commit, it works list a charm!

I can confirm that it works with my Gnome 3.28.4 on Ubuntu 18.04

**Pull request merged**
