### PR TITLE
French translation update

### PR DESCRIPTION
**Pull request by DevDef**
Please pull in this French translation update

### CODE REVIEW

**Comment by chrisspen** [comment]
Thanks for the contribution. However, are you sure about the translation for "nice"? `Nice` in this context is the name of a program and a proper noun, not the adjective "nice".

**Comment by franglais125** [comment]
I don't feel strongly about it. While `nice` is the kernel utility, "politesse" refers to the concept [1], so I think it's ok to translate the string.

@DevDef the only thing that I'm not sure about is modifying "R" and "W" for "en lecture" and "en écriture". The reason is that it clutters a bit the menu. Maybe a shorter version? Like "lecture" and "écriture"? Also, thanks for the PR :)

[1] http://www.man-linux-magique.net/man2/nice.html

**Comment by DevDef** [comment]
> I don't feel strongly about it. While nice is the kernel utility, "politesse" refers to the concept [1], so I think it's ok to translate the string.

I found that “politesse” was a pretty elegant translation (already seen elsewhere). ;-)

> @DevDef the only thing that I'm not sure about is modifying "R" and "W" for "en lecture" and "en écriture". The reason is that it clutters a bit the menu. Maybe a shorter version? Like "lecture" and "écriture"?

@franglais125: With such an alias, I guess you are French or, at least, French is your native language. So, I’m sure that you will find really ugly to have something like “12 Mio/s lecture”.
I didn’t find something shorter than “en lecture” and “en écriture”. But, you know, there’s already “descendant” and “montant” on the line above, so it’s almost the same width…

> Also, thanks for the PR :)

Your welcome. :-)
Also, for a better localization, please take care of the number format by using Number.toLocaleString(_locale_) ([issue #360](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/360)). TIA.

**Comment by franglais125** [comment]
@DevDef ok, agreed on all points! And yes, I do speak French, but use gnome in the English locale, hence why I don't notice these things you reported, merci encore.

As for the the `toLocaleString`... I was trying to prepare an overhaul of the locale work (checkout my branches). I'm a bit behind, and don't have that much time these days, but yes, it's something I want to fix eventually.

**Comment by DevDef** [comment]
I’m glad to see that you are already taking care of the localized number format. :-)
Cheers,

Davy

**Pull request merged**
