### PR TITLE
Temperature threshold alert.

### PR DESCRIPTION
**Pull request by franglais125**
* This adds a new setting (temperature-threshold). When the temperature
passes the threshold, the text on the top bar is displayed in red.
 * I had to tweak the fahrenheit code so that this works with Celsius
and Fahrenheit.
 * When set to 0, this is disabled (and this is the default behavior).
 * We could add a notification too, but I'll leave it as it is for now.

Screenshot of the idea:

screenshot from 2017-05-16 01-02-20

### CODE REVIEW

**Comment by Ecron** [comment]
Amazing feature!! 👏

**Comment by hackel** [comment]
This looks great!  I have one feature request for the future...an option to only show the temperature at all when it's over the threshold would be most welcome.

**Comment by DevDef** [comment]
Please take care of the localization files by running xgettext and msgmerge to include the new string “Temperature threshold (0 to disable)” in all the `.po` files.

**Comment by franglais125** [comment]
Done! I included the Spanish and French translations.

**Comment by DevDef** [comment]
> Done! I included the Spanish and French translations.

That’s very nice of you!

**Pull request merged**
