### PR TITLE
Gnome shell 40

### PR DESCRIPTION
**Pull request by NVieville**
Hello,

I wonder if you could please merge this pull request to master branch. 

It contains 2 commits.

One to allow preferences window to be displayed (had to fix methods 
names for GtkBox according to https://gjs.guide/extensions/upgrading/gnome-shell-40.html#adding-to-the-containers).

The second one avoids extension warnings in gnome-shell journal (journalctl -qxe).

Feel free to make any comment about this subject.

Cordially,

-- 
NVieville

### CODE REVIEW

**Review by Varun-garg — APPROVED** [review]

**Comment by Its-Alex** [comment]
@NVieville After trying with your patch I have a glitch with the font. I think that the old text is not clear before replacing new text. :thinking: 

I can't take a screenshot because this refresh perfectly when I freeze the screen to take a screenshot :confused:

**Comment by NVieville** [comment]
Hello,

@Its-Alex could be please try to explain what does and where occurs the glitch you noticed? For my part, I didn't notice some problems with fonts, but maybe I'm not looking at the right place. For information, Fedora 34 here with standard Fedora gnome-shell-extension-system-monitor-applet package installed.

Thank for your feedback.

Cordially,


-- 
NVieville

**Comment by dgoodwin** [comment]
Installed manually from @NVieville branch and looks good here. Glad to have this applet back, it's so useful!

**Comment by NVieville** [comment]
Hello,

@Its-Alex The visual glitch with the font maybe corresponds to the issue reported here? 
https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/685 

Cordially,


-- 
NVieville

**Comment by Its-Alex** [comment]
Hello @NVieville,

Sorry for my late answer, this is exactly my problem!

Thanks!

**Pull request merged**
