### PR TITLE
Small feature: add "left" as an option for indicator position

### PR DESCRIPTION
**Pull request by franglais125**
Comments and suggestions welcome! If I can get some testers for this it would be great, just to make sure I don't introduce regressions.

(cc @jtmkrueger and @CharoSW)

----------------------------------------------------------------

Edit: btw, Travis is failing again... So I don't yet know if the coding style is up to the standard.

Error:
```
The command "curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -" failed and exited with 1 during .
```

### CODE REVIEW

**Comment by CharoSW** [comment]
As another gnome release has come and this seems to have no conflicts can we get this merged.  As I have said in #365 my workflow includes having this option and it would be nice to go back to the master branch without having to hack it in myself

**Comment by chrisspen** [comment]
@franglais125 Is this still something you're interested in pursuing? If so, could you please resolve conflicts?

**Comment by franglais125** [comment]
I resolved all conflicts. Just needs review and testing. Cheers.

**Comment by chrisspen** [comment]
There's still one more small conflict.

**Comment by chrisspen** [comment]
Feel free to re-open if you can fix the conflicts.

**Comment by Timboooh** [comment]
Any news on this PR? If not, I'd like to take a crack at it

**Pull request closed without merging**
