### PR TITLE
Fix showing in top-left corner

### PR DESCRIPTION
**Pull request by Daemo00**
Fix https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/633

Just a first attempt to fix the linked issue, mostly done by reverse-engineering the changes in https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1380 :sweat_smile:, but I tried locally and it fixes the issue for me.

### CODE REVIEW

**Comment by DevDef** [comment]
@Daemo00 I’ve included your fix in #660 that is now merged, so you can close this pull request.
Good job, BTW. :-)

**Comment by bluet** [comment]
@DevDef I'm testing master branch https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/tree/0dfdaa99643b4762bcfc09279bc987703cb02db9 but still experiencing this bug with Ubuntu 18.04 (Gnome 3.28).

Anything I missed?

**Comment by DevDef** [comment]
@bluet Perhaps the fix doesn’t work with GNOME 3.28. I’m running 3.38 on Mageia 8.
Could you consider upgrading to a more recent version of Ubuntu (20.04 LTS or 20.10)?

**Comment by bluet** [comment]
@DevDef ah I see.

Our primary computers (including the one I'm using, for example) stays in one generation behind latest LTS version of Ubuntu for maximum stability considerations, so....

Sadly I don't have the chance to enjoy the fixed system monitor extension. Thanks still for your information. :-)

**Pull request closed without merging**
